
import os
import django
import sys

# Setup Django Environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from core.models import UseCase

def update_usecase_titles():
    updates = {
        "Kushagramati Master Use Case List V1.2(1) 10": "Migration from Cloudera to Databricks",
        "Kushagramati Master Use Case List V1.2(1) 12": "Contracts Data Integration and BI Reporting - SAP data to databricks"
    }

    print("Updating Use Case titles...")

    for old_title, new_title in updates.items():
        # Using exact match for the title generated by my script earlier
        ucs = UseCase.objects.filter(title__iexact=old_title)
        if ucs.exists():
            for uc in ucs:
                uc.title = new_title
                uc.save()
                print(f"Updated: '{old_title}' -> '{new_title}'")
        else:
            # Maybe the title has slightly different spacing due to earlier processing
            # Re-generate what the title would have been: filename with dashes/underscores replaced by spaces
            print(f"Not found: '{old_title}'")

if __name__ == '__main__':
    update_usecase_titles()
