# Generated by Django 5.0.1 on 2026-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('HOME', 'Home Page'), ('ABOUT', 'About Page'), ('SERVICES', 'Services Page'), ('CONTACT', 'Contact Page'), ('INDUSTRIES', 'Industries Page'), ('CAREERS', 'Careers Page'), ('BLOG', 'Blog Page')], default='HOME', max_length=20),
        ),
    ]
