# Generated by Django 6.0.1 on 2026-01-29 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='careerjob',
            name='application_link',
            field=models.URLField(blank=True, help_text='Link to external application form if applicable'),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='Remote Available'),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g. $80k - $100k', max_length=100),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.department'),
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('HOME', 'Home Page'), ('ABOUT', 'About Page'), ('CAREERS', 'Careers Page')], max_length=20)),
                ('section_key', models.CharField(choices=[('OPEN_POSITIONS', 'Open Positions')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('page', 'section_key')},
            },
        ),
    ]
