# Generated by Django 5.0.1 on 2026-01-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_casestudy_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='case_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industries', to='core.casestudy'),
        ),
    ]
