# Generated by Django 5.0.1 on 2026-01-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_careerjob_application_link_and_more'),
        ('core', '0004_industry_case_study'),
    ]

    operations = [
    ]
