# Generated by Django 5.0.1 on 2026-01-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260129_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed content for the Read More view'),
        ),
        migrations.AddField(
            model_name='tool',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed content for the Read More view'),
        ),
    ]
