# Generated by Django 5.0.1 on 2026-02-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_casestudy_content_tool_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DATABRICKS', 'Databricks'), ('MIGRATION', 'Migration'), ('AI_ML', 'AI/ML'), ('OPTIMIZATION', 'Performance Optimization'), ('UNITY_CATALOG', 'Unity Catalog'), ('OTHER', 'Other')], default='DATABRICKS', max_length=50)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('approach', models.TextField()),
                ('benefits', models.TextField(help_text='List of benefits, will be split by newlines')),
                ('image', models.ImageField(blank=True, null=True, upload_to='usecases/images/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
