# Generated by Django 5.0.1 on 2026-02-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usecase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.CharField(choices=[('DATABRICKS', 'Databricks'), ('AI_APP_DEV', 'AI Application Development'), ('OTHER', 'Other')], default='DATABRICKS', max_length=50),
        ),
    ]
